name: commit_test
on:
  push: #设置触发规则
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code #这部分是为了从github自动clone代码
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install build tools #这部分是安装依赖
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake wget
      - name: Download mnist data
        run: |
          cd src
          mkdir -p ./demo/mnist/mnist
          wget https://gitee.com/chenxuan520/deeplearning/releases/download/v0.0.1-beta/t10k-labels-idx1-ubyte -O ./demo/mnist/mnist/t10k-labels-idx1-ubyte
          wget https://gitee.com/chenxuan520/deeplearning/releases/download/v0.0.1-beta/train-labels-idx1-ubyte -O ./demo/mnist/mnist/train-labels-idx1-ubyte
          wget https://gitee.com/chenxuan520/deeplearning/releases/download/v0.0.1-beta/t10k-images-idx3-ubyte -O ./demo/mnist/mnist/t10k-images-idx3-ubyte
          wget https://gitee.com/chenxuan520/deeplearning/releases/download/v0.0.1-beta/train-images-idx3-ubyte -O ./demo/mnist/mnist/train-images-idx3-ubyte
          cd ..
      - name: Run test #需要执行的命令
        run: |
          cd src
          ./build.sh
          ./bin/test_bin
          ./bin/mnist
